// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use parol_runtime::id_tree::Tree;
use parol_runtime::lexer::{TokenStream, Tokenizer};
use parol_runtime::miette::Result;
use parol_runtime::once_cell::sync::Lazy;
#[allow(unused_imports)]
use parol_runtime::parser::{
    DFATransition, LLKParser, LookaheadDFA, ParseTreeType, ParseType, Production,
};
use std::cell::RefCell;
use std::path::Path;

use crate::skill_grammar::SkillGrammar;
use crate::skill_grammar_trait::SkillGrammarAuto;

use parol_runtime::lexer::tokenizer::{
    ERROR_TOKEN, NEW_LINE_TOKEN, UNMATCHABLE_TOKEN, WHITESPACE_TOKEN,
};

pub const TERMINALS: &[&str; 28] = &[
    /*  0 */ UNMATCHABLE_TOKEN,
    /*  1 */ UNMATCHABLE_TOKEN,
    /*  2 */ UNMATCHABLE_TOKEN,
    /*  3 */ UNMATCHABLE_TOKEN,
    /*  4 */ UNMATCHABLE_TOKEN,
    /*  5 */ r###"火"###,
    /*  6 */ r###"水"###,
    /*  7 */ r###"木"###,
    /*  8 */ r###"光"###,
    /*  9 */ r###"闇"###,
    /* 10 */ r###"回復"###,
    /* 11 */ r###"お邪魔"###,
    /* 12 */ r###"爆弾"###,
    /* 13 */ r###"毒"###,
    /* 14 */ r###"猛毒"###,
    /* 15 */ r###"変化"###,
    /* 16 */ r###"ドロップ"###,
    /* 17 */ r###"全"###,
    /* 18 */ r###"5属性"###,
    /* 19 */ r###"ランダム"###,
    /* 20 */ r###"入れ替える"###,
    /* 21 */ r###"を"###,
    /* 22 */ r###"に"###,
    /* 23 */ r###"で"###,
    /* 24 */ r###"\+"###,
    /* 25 */ r###"、"###,
    /* 26 */ r###"。"###,
    /* 27 */ ERROR_TOKEN,
];

pub const TERMINAL_NAMES: &[&str; 28] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "Fire",
    /*  6 */ "Water",
    /*  7 */ "Wood",
    /*  8 */ "Lightning",
    /*  9 */ "Dark",
    /* 10 */ "Recovery",
    /* 11 */ "Disturb",
    /* 12 */ "Bomb",
    /* 13 */ "Poison",
    /* 14 */ "DeadlyPoison",
    /* 15 */ "WordChange",
    /* 16 */ "WordDrop",
    /* 17 */ "WordAll",
    /* 18 */ "WordFiveAttribute",
    /* 19 */ "WordRandom",
    /* 20 */ "WordReplace",
    /* 21 */ "Wo",
    /* 22 */ "Ni",
    /* 23 */ "So",
    /* 24 */ "Plus",
    /* 25 */ "Camma",
    /* 26 */ "Period",
    /* 27 */ "Error",
];

/* SCANNER_0: "INITIAL" */
const SCANNER_0: (&[&str; 5], &[usize; 22]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ NEW_LINE_TOKEN,
        /*  2 */ WHITESPACE_TOKEN,
        /*  3 */ UNMATCHABLE_TOKEN,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[
        5,  /* Fire */
        6,  /* Water */
        7,  /* Wood */
        8,  /* Lightning */
        9,  /* Dark */
        10, /* Recovery */
        11, /* Disturb */
        12, /* Bomb */
        13, /* Poison */
        14, /* DeadlyPoison */
        15, /* WordChange */
        16, /* WordDrop */
        17, /* WordAll */
        18, /* WordFiveAttribute */
        19, /* WordRandom */
        20, /* WordReplace */
        21, /* Wo */
        22, /* Ni */
        23, /* So */
        24, /* Plus */
        25, /* Camma */
        26, /* Period */
    ],
);

const MAX_K: usize = 1;

pub const NON_TERMINALS: &[&str; 42] = &[
    /*  0 */ "AllDrops",
    /*  1 */ "Bomb",
    /*  2 */ "Camma",
    /*  3 */ "ChangeAllOfBoradBlock",
    /*  4 */ "ChangeAllOfBoradStmt",
    /*  5 */ "ChangeDropBlock",
    /*  6 */ "ChangeDropStmt",
    /*  7 */ "ChangeDropStmtList",
    /*  8 */ "Color",
    /*  9 */ "Dark",
    /* 10 */ "DeadlyPoison",
    /* 11 */ "Disturb",
    /* 12 */ "Drop",
    /* 13 */ "DropOpt",
    /* 14 */ "DropOpt0",
    /* 15 */ "DropRefreshStmt",
    /* 16 */ "Drops",
    /* 17 */ "DropsList",
    /* 18 */ "DropsList0",
    /* 19 */ "Fire",
    /* 20 */ "FiveAttribute",
    /* 21 */ "FiveAttributeOpt",
    /* 22 */ "Lightning",
    /* 23 */ "Line",
    /* 24 */ "ManyDrop",
    /* 25 */ "Ni",
    /* 26 */ "NonColoredDrop",
    /* 27 */ "Period",
    /* 28 */ "Plus",
    /* 29 */ "Poison",
    /* 30 */ "Recovery",
    /* 31 */ "SkillLines",
    /* 32 */ "So",
    /* 33 */ "Water",
    /* 34 */ "Wo",
    /* 35 */ "Wood",
    /* 36 */ "WordAll",
    /* 37 */ "WordChange",
    /* 38 */ "WordDrop",
    /* 39 */ "WordFiveAttribute",
    /* 40 */ "WordRandom",
    /* 41 */ "WordReplace",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 42] = &[
    /* 0 - "AllDrops" */
    LookaheadDFA {
        states: &[Some(19)],
        transitions: &[],
        k: 0,
    },
    /* 1 - "Bomb" */
    LookaheadDFA {
        states: &[Some(46)],
        transitions: &[],
        k: 0,
    },
    /* 2 - "Camma" */
    LookaheadDFA {
        states: &[Some(59)],
        transitions: &[],
        k: 0,
    },
    /* 3 - "ChangeAllOfBoradBlock" */
    LookaheadDFA {
        states: &[Some(10)],
        transitions: &[],
        k: 0,
    },
    /* 4 - "ChangeAllOfBoradStmt" */
    LookaheadDFA {
        states: &[Some(7)],
        transitions: &[],
        k: 0,
    },
    /* 5 - "ChangeDropBlock" */
    LookaheadDFA {
        states: &[Some(9)],
        transitions: &[],
        k: 0,
    },
    /* 6 - "ChangeDropStmt" */
    LookaheadDFA {
        states: &[Some(4)],
        transitions: &[],
        k: 0,
    },
    /* 7 - "ChangeDropStmtList" */
    LookaheadDFA {
        states: &[None, Some(5), Some(6)],
        transitions: &[DFATransition(0, 15, 2), DFATransition(0, 25, 1)],
        k: 1,
    },
    /* 8 - "Color" */
    LookaheadDFA {
        states: &[None, Some(34), Some(35), Some(36), Some(37), Some(38)],
        transitions: &[
            DFATransition(0, 5, 1),
            DFATransition(0, 6, 2),
            DFATransition(0, 7, 3),
            DFATransition(0, 8, 4),
            DFATransition(0, 9, 5),
        ],
        k: 1,
    },
    /* 9 - "Dark" */
    LookaheadDFA {
        states: &[Some(43)],
        transitions: &[],
        k: 0,
    },
    /* 10 - "DeadlyPoison" */
    LookaheadDFA {
        states: &[Some(48)],
        transitions: &[],
        k: 0,
    },
    /* 11 - "Disturb" */
    LookaheadDFA {
        states: &[Some(45)],
        transitions: &[],
        k: 0,
    },
    /* 12 - "Drop" */
    LookaheadDFA {
        states: &[None, Some(23), Some(24)],
        transitions: &[
            DFATransition(0, 5, 1),
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 1),
            DFATransition(0, 8, 1),
            DFATransition(0, 9, 1),
            DFATransition(0, 10, 2),
            DFATransition(0, 11, 2),
            DFATransition(0, 12, 2),
            DFATransition(0, 13, 2),
            DFATransition(0, 14, 2),
        ],
        k: 1,
    },
    /* 13 - "DropOpt" */
    LookaheadDFA {
        states: &[None, Some(27), Some(28)],
        transitions: &[
            DFATransition(0, 16, 1),
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
        ],
        k: 1,
    },
    /* 14 - "DropOpt0" */
    LookaheadDFA {
        states: &[None, Some(25), Some(26)],
        transitions: &[
            DFATransition(0, 16, 1),
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
        ],
        k: 1,
    },
    /* 15 - "DropRefreshStmt" */
    LookaheadDFA {
        states: &[Some(8)],
        transitions: &[],
        k: 0,
    },
    /* 16 - "Drops" */
    LookaheadDFA {
        states: &[None, Some(11), Some(14)],
        transitions: &[
            DFATransition(0, 5, 1),
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 1),
            DFATransition(0, 8, 1),
            DFATransition(0, 9, 1),
            DFATransition(0, 10, 1),
            DFATransition(0, 11, 1),
            DFATransition(0, 12, 1),
            DFATransition(0, 13, 1),
            DFATransition(0, 14, 1),
            DFATransition(0, 18, 2),
        ],
        k: 1,
    },
    /* 17 - "DropsList" */
    LookaheadDFA {
        states: &[None, Some(12), Some(13)],
        transitions: &[
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 24, 1),
            DFATransition(0, 25, 1),
        ],
        k: 1,
    },
    /* 18 - "DropsList0" */
    LookaheadDFA {
        states: &[None, Some(15), Some(16)],
        transitions: &[
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 24, 1),
            DFATransition(0, 25, 1),
        ],
        k: 1,
    },
    /* 19 - "Fire" */
    LookaheadDFA {
        states: &[Some(39)],
        transitions: &[],
        k: 0,
    },
    /* 20 - "FiveAttribute" */
    LookaheadDFA {
        states: &[Some(20)],
        transitions: &[],
        k: 0,
    },
    /* 21 - "FiveAttributeOpt" */
    LookaheadDFA {
        states: &[None, Some(21), Some(22)],
        transitions: &[
            DFATransition(0, 16, 1),
            DFATransition(0, 21, 2),
            DFATransition(0, 22, 2),
            DFATransition(0, 24, 2),
            DFATransition(0, 25, 2),
        ],
        k: 1,
    },
    /* 22 - "Lightning" */
    LookaheadDFA {
        states: &[Some(42)],
        transitions: &[],
        k: 0,
    },
    /* 23 - "Line" */
    LookaheadDFA {
        states: &[None, Some(1), Some(2), Some(3)],
        transitions: &[
            DFATransition(0, 5, 1),
            DFATransition(0, 6, 1),
            DFATransition(0, 7, 1),
            DFATransition(0, 8, 1),
            DFATransition(0, 9, 1),
            DFATransition(0, 10, 1),
            DFATransition(0, 11, 1),
            DFATransition(0, 12, 1),
            DFATransition(0, 13, 1),
            DFATransition(0, 14, 1),
            DFATransition(0, 17, 2),
            DFATransition(0, 18, 1),
            DFATransition(0, 19, 3),
        ],
        k: 1,
    },
    /* 24 - "ManyDrop" */
    LookaheadDFA {
        states: &[None, Some(17), Some(18)],
        transitions: &[DFATransition(0, 24, 2), DFATransition(0, 25, 1)],
        k: 1,
    },
    /* 25 - "Ni" */
    LookaheadDFA {
        states: &[Some(56)],
        transitions: &[],
        k: 0,
    },
    /* 26 - "NonColoredDrop" */
    LookaheadDFA {
        states: &[None, Some(29), Some(30), Some(31), Some(32), Some(33)],
        transitions: &[
            DFATransition(0, 10, 1),
            DFATransition(0, 11, 2),
            DFATransition(0, 12, 3),
            DFATransition(0, 13, 4),
            DFATransition(0, 14, 5),
        ],
        k: 1,
    },
    /* 27 - "Period" */
    LookaheadDFA {
        states: &[Some(60)],
        transitions: &[],
        k: 0,
    },
    /* 28 - "Plus" */
    LookaheadDFA {
        states: &[Some(58)],
        transitions: &[],
        k: 0,
    },
    /* 29 - "Poison" */
    LookaheadDFA {
        states: &[Some(47)],
        transitions: &[],
        k: 0,
    },
    /* 30 - "Recovery" */
    LookaheadDFA {
        states: &[Some(44)],
        transitions: &[],
        k: 0,
    },
    /* 31 - "SkillLines" */
    LookaheadDFA {
        states: &[Some(0)],
        transitions: &[],
        k: 0,
    },
    /* 32 - "So" */
    LookaheadDFA {
        states: &[Some(57)],
        transitions: &[],
        k: 0,
    },
    /* 33 - "Water" */
    LookaheadDFA {
        states: &[Some(40)],
        transitions: &[],
        k: 0,
    },
    /* 34 - "Wo" */
    LookaheadDFA {
        states: &[Some(55)],
        transitions: &[],
        k: 0,
    },
    /* 35 - "Wood" */
    LookaheadDFA {
        states: &[Some(41)],
        transitions: &[],
        k: 0,
    },
    /* 36 - "WordAll" */
    LookaheadDFA {
        states: &[Some(51)],
        transitions: &[],
        k: 0,
    },
    /* 37 - "WordChange" */
    LookaheadDFA {
        states: &[Some(49)],
        transitions: &[],
        k: 0,
    },
    /* 38 - "WordDrop" */
    LookaheadDFA {
        states: &[Some(50)],
        transitions: &[],
        k: 0,
    },
    /* 39 - "WordFiveAttribute" */
    LookaheadDFA {
        states: &[Some(52)],
        transitions: &[],
        k: 0,
    },
    /* 40 - "WordRandom" */
    LookaheadDFA {
        states: &[Some(53)],
        transitions: &[],
        k: 0,
    },
    /* 41 - "WordReplace" */
    LookaheadDFA {
        states: &[Some(54)],
        transitions: &[],
        k: 0,
    },
];

pub const PRODUCTIONS: &[Production; 61] = &[
    // 0 - SkillLines: Line Period;
    Production {
        lhs: 31,
        production: &[ParseType::N(27), ParseType::N(23)],
    },
    // 1 - Line: ChangeDropStmt;
    Production {
        lhs: 23,
        production: &[ParseType::N(6)],
    },
    // 2 - Line: ChangeAllOfBoradStmt;
    Production {
        lhs: 23,
        production: &[ParseType::N(4)],
    },
    // 3 - Line: DropRefreshStmt;
    Production {
        lhs: 23,
        production: &[ParseType::N(15)],
    },
    // 4 - ChangeDropStmt: ChangeDropBlock ChangeDropStmtList /* Vec */ WordChange;
    Production {
        lhs: 6,
        production: &[ParseType::N(37), ParseType::N(7), ParseType::N(5)],
    },
    // 5 - ChangeDropStmtList: Camma ChangeDropBlock ChangeDropStmtList;
    Production {
        lhs: 7,
        production: &[ParseType::N(7), ParseType::N(5), ParseType::N(2)],
    },
    // 6 - ChangeDropStmtList: ;
    Production {
        lhs: 7,
        production: &[],
    },
    // 7 - ChangeAllOfBoradStmt: AllDrops Wo ChangeAllOfBoradBlock Ni WordChange;
    Production {
        lhs: 4,
        production: &[
            ParseType::N(37),
            ParseType::N(25),
            ParseType::N(3),
            ParseType::N(34),
            ParseType::N(0),
        ],
    },
    // 8 - DropRefreshStmt: WordRandom So WordDrop Wo WordReplace;
    Production {
        lhs: 15,
        production: &[
            ParseType::N(41),
            ParseType::N(34),
            ParseType::N(38),
            ParseType::N(32),
            ParseType::N(40),
        ],
    },
    // 9 - ChangeDropBlock: Drops Wo Drop Ni;
    Production {
        lhs: 5,
        production: &[
            ParseType::N(25),
            ParseType::N(12),
            ParseType::N(34),
            ParseType::N(16),
        ],
    },
    // 10 - ChangeAllOfBoradBlock: Drops;
    Production {
        lhs: 3,
        production: &[ParseType::N(16)],
    },
    // 11 - Drops: Drop DropsList /* Vec */;
    Production {
        lhs: 16,
        production: &[ParseType::N(17), ParseType::N(12)],
    },
    // 12 - DropsList: ManyDrop DropsList;
    Production {
        lhs: 17,
        production: &[ParseType::N(17), ParseType::N(24)],
    },
    // 13 - DropsList: ;
    Production {
        lhs: 17,
        production: &[],
    },
    // 14 - Drops: FiveAttribute DropsList0 /* Vec */;
    Production {
        lhs: 16,
        production: &[ParseType::N(18), ParseType::N(20)],
    },
    // 15 - DropsList0: ManyDrop DropsList0;
    Production {
        lhs: 18,
        production: &[ParseType::N(18), ParseType::N(24)],
    },
    // 16 - DropsList0: ;
    Production {
        lhs: 18,
        production: &[],
    },
    // 17 - ManyDrop: Camma Drop;
    Production {
        lhs: 24,
        production: &[ParseType::N(12), ParseType::N(2)],
    },
    // 18 - ManyDrop: Plus Drop;
    Production {
        lhs: 24,
        production: &[ParseType::N(12), ParseType::N(28)],
    },
    // 19 - AllDrops: WordAll WordDrop;
    Production {
        lhs: 0,
        production: &[ParseType::N(38), ParseType::N(36)],
    },
    // 20 - FiveAttribute: WordFiveAttribute FiveAttributeOpt /* Option */;
    Production {
        lhs: 20,
        production: &[ParseType::N(21), ParseType::N(39)],
    },
    // 21 - FiveAttributeOpt: WordDrop;
    Production {
        lhs: 21,
        production: &[ParseType::N(38)],
    },
    // 22 - FiveAttributeOpt: ;
    Production {
        lhs: 21,
        production: &[],
    },
    // 23 - Drop: Color DropOpt /* Option */;
    Production {
        lhs: 12,
        production: &[ParseType::N(13), ParseType::N(8)],
    },
    // 24 - Drop: NonColoredDrop DropOpt0 /* Option */;
    Production {
        lhs: 12,
        production: &[ParseType::N(14), ParseType::N(26)],
    },
    // 25 - DropOpt0: WordDrop;
    Production {
        lhs: 14,
        production: &[ParseType::N(38)],
    },
    // 26 - DropOpt0: ;
    Production {
        lhs: 14,
        production: &[],
    },
    // 27 - DropOpt: WordDrop;
    Production {
        lhs: 13,
        production: &[ParseType::N(38)],
    },
    // 28 - DropOpt: ;
    Production {
        lhs: 13,
        production: &[],
    },
    // 29 - NonColoredDrop: Recovery;
    Production {
        lhs: 26,
        production: &[ParseType::N(30)],
    },
    // 30 - NonColoredDrop: Disturb;
    Production {
        lhs: 26,
        production: &[ParseType::N(11)],
    },
    // 31 - NonColoredDrop: Bomb;
    Production {
        lhs: 26,
        production: &[ParseType::N(1)],
    },
    // 32 - NonColoredDrop: Poison;
    Production {
        lhs: 26,
        production: &[ParseType::N(29)],
    },
    // 33 - NonColoredDrop: DeadlyPoison;
    Production {
        lhs: 26,
        production: &[ParseType::N(10)],
    },
    // 34 - Color: Fire;
    Production {
        lhs: 8,
        production: &[ParseType::N(19)],
    },
    // 35 - Color: Water;
    Production {
        lhs: 8,
        production: &[ParseType::N(33)],
    },
    // 36 - Color: Wood;
    Production {
        lhs: 8,
        production: &[ParseType::N(35)],
    },
    // 37 - Color: Lightning;
    Production {
        lhs: 8,
        production: &[ParseType::N(22)],
    },
    // 38 - Color: Dark;
    Production {
        lhs: 8,
        production: &[ParseType::N(9)],
    },
    // 39 - Fire: "火";
    Production {
        lhs: 19,
        production: &[ParseType::T(5)],
    },
    // 40 - Water: "水";
    Production {
        lhs: 33,
        production: &[ParseType::T(6)],
    },
    // 41 - Wood: "木";
    Production {
        lhs: 35,
        production: &[ParseType::T(7)],
    },
    // 42 - Lightning: "光";
    Production {
        lhs: 22,
        production: &[ParseType::T(8)],
    },
    // 43 - Dark: "闇";
    Production {
        lhs: 9,
        production: &[ParseType::T(9)],
    },
    // 44 - Recovery: "回復";
    Production {
        lhs: 30,
        production: &[ParseType::T(10)],
    },
    // 45 - Disturb: "お邪魔";
    Production {
        lhs: 11,
        production: &[ParseType::T(11)],
    },
    // 46 - Bomb: "爆弾";
    Production {
        lhs: 1,
        production: &[ParseType::T(12)],
    },
    // 47 - Poison: "毒";
    Production {
        lhs: 29,
        production: &[ParseType::T(13)],
    },
    // 48 - DeadlyPoison: "猛毒";
    Production {
        lhs: 10,
        production: &[ParseType::T(14)],
    },
    // 49 - WordChange: "変化";
    Production {
        lhs: 37,
        production: &[ParseType::T(15)],
    },
    // 50 - WordDrop: "ドロップ";
    Production {
        lhs: 38,
        production: &[ParseType::T(16)],
    },
    // 51 - WordAll: "全";
    Production {
        lhs: 36,
        production: &[ParseType::T(17)],
    },
    // 52 - WordFiveAttribute: "5属性";
    Production {
        lhs: 39,
        production: &[ParseType::T(18)],
    },
    // 53 - WordRandom: "ランダム";
    Production {
        lhs: 40,
        production: &[ParseType::T(19)],
    },
    // 54 - WordReplace: "入れ替える";
    Production {
        lhs: 41,
        production: &[ParseType::T(20)],
    },
    // 55 - Wo: "を";
    Production {
        lhs: 34,
        production: &[ParseType::T(21)],
    },
    // 56 - Ni: "に";
    Production {
        lhs: 25,
        production: &[ParseType::T(22)],
    },
    // 57 - So: "で";
    Production {
        lhs: 32,
        production: &[ParseType::T(23)],
    },
    // 58 - Plus: "\+";
    Production {
        lhs: 28,
        production: &[ParseType::T(24)],
    },
    // 59 - Camma: "、";
    Production {
        lhs: 2,
        production: &[ParseType::T(25)],
    },
    // 60 - Period: "。";
    Production {
        lhs: 27,
        production: &[ParseType::T(26)],
    },
];

static TOKENIZERS: Lazy<Vec<(&'static str, Tokenizer)>> = Lazy::new(|| {
    vec![(
        "INITIAL",
        Tokenizer::build(TERMINALS, SCANNER_0.0, SCANNER_0.1).unwrap(),
    )]
});

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut SkillGrammar<'t>,
) -> Result<Tree<ParseTreeType<'t>>>
where
    T: AsRef<Path>,
{
    let mut llk_parser = LLKParser::new(
        31,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    let token_stream =
        RefCell::new(TokenStream::new(input, file_name, &TOKENIZERS, MAX_K).unwrap());
    // Initialize wrapper
    let mut user_actions = SkillGrammarAuto::new(user_actions);
    let result = llk_parser.parse(token_stream, &mut user_actions);
    match result {
        Ok(()) => Ok(llk_parser.parse_tree),
        Err(e) => Err(e),
    }
}
